name: durt_online_demo
description: Durt Online demo
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2   # <-- analyze için lint paketi

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
    - assets/backs/
    - assets/ui/        # <-- DÜZELTİLDİ (küçük harf)
    - assets/tables/
