name: durt_online_demo
description: Durt Online demo project with Flutter + SVG assets
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

flutter_icons:
  android: true
  ios: false              # <<< iOS kapalı
  image_path: "brand/app_icon_1024.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9   # SVG’leri göstermek için

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
    - assets/backs/
    - assets/ui/
    - assets/tables/
