name: Android APK Build (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Ensure android project
        run: flutter create . --platforms=android

      - name: Clean
        run: flutter clean

      # 1) Standart Flutter build
      - name: Build APK (debug)
        run: flutter build apk --debug -v

      # 2) Flutter build FAIL olursa, Gradle ile ayrıntılı stacktrace dene
      - name: Gradle fallback (stacktrace)
        if: failure()
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace --warning-mode all

      # 3) APK neredeyse oradan yükle (her iki yol da ekli)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            android/app/build/outputs/apk/debug/app-debug.apk
