name: Android APK Build (Debug)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Ensure android project
        run: flutter create . --platforms=android

      - name: Clean
        run: flutter clean

      - name: Flutter analyze
        run: flutter analyze
        continue-on-error: true

      - name: Build APK (debug)
        run: flutter build apk --debug -v -

      - name: Debug list (on failure)
        if: failure()
        run: |
          ls -la
          ls -la assets
          ls -la assets/ui
          ls -la build/app/outputs/flutter-apk || true

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
