name: Android APK Build (Debug)

on:
  workflow_dispatch: {}   # elle çalıştırma

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter --version
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      # Repo'da android yoksa CI'da üret
      - name: Create Android platform
        run: flutter create . --platforms=android

      - name: Flutter clean
        run: flutter clean

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
