name: Android APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable 3.19.6)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'   # <<--- SÜRÜMÜ SABİTLE
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # (Opsiyonel ama faydalı)
      - name: Generate launcher icons
        run: dart run flutter_launcher_icons:main

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: durt-online-demo-apk
          path: build/app/outputs/flutter-apk/app-release.apk
